### ISSUE TITLE
ImportError on Windows: distro.id() call in BrokenPlatform.py causes failure

### ISSUE THREAD

**Issue by drmbt** [BrokenSource/BrokenSource#26]
### Operating system

💠 Windows 11

### Runtime method

📦 PyApp executables, N/A

### Project version

0.8.0.dev0

### Python version

Python 3.11

### GPU Brand

🟢 NVIDIA Desktop

### GPU Model

3090ti

### Description

On Windows, importing Broken fails due to an unconditional call to distro.id() in Core/BrokenPlatform.py. The distro package tries to run uname, which does not exist on Windows, resulting in a subprocess.CalledProcessError.
Quick fix:
Wrap the distro.id() call with a platform check:
```
if Name == "linux":
    LinuxDistro: str = distro.id()
else:
    LinuxDistro: str = ""
```
This prevents the error and allows the package to import on Windows

### Traceback

```shell

```
